# Configuration Constants
DEFAULT_GEN_OLLAMA_MODEL: 'qwen2.5:7b'
DEFAULT_RET_OLLAMA_MODEL: 'qwen2.5:7b'
DEFAULT_GEN_TEMPERATURE: 0.1
DEFAULT_RET_TEMPERATURE: 0.0
DEFAULT_NUM_QUESTIONS: 10
DEFAULT_TEMPLATE: "default"
MAX_GEN_PROMPT_CONTENT_LEN: 8000
DEFAULT_OUTPUT_DIR: "datasets"
SUPPORTED_TEMPLATES: ["default", "gemma", "llama"]
SUPPORTED_FILE_TYPES: [".txt", ".pdf"]